config/routes.rb
Rails.application.routes.draw do
  root 'weather#index'

  scope 'weather', controller: :weather do
    get :current
    get 'by_time', as: 'by_time_weather'
    get 'historical', :historical
    get 'historical/max', to: 'weather#historical_max'
    get 'historical/min', to: 'weather#historical_min'
    get 'historical/avg', to: 'weather#historical_avg'
  end

  get '/health', to: 'application#health'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def health
    render plain: 'OK'
  end
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  include Constants

  before_action :set_historical_hourly_data, only: [:historical, :historical_avg, :by_time]
  before_action :set_historical_details_data, only: [:historical_max, :historical_min]
  def current
    current_data = WeatherServiceCurrent.new.get_data_with_caching
    format_and_render(current_data, 'weather/current')
  end

  def historical
    format_and_render(@historical_hourly_data, 'weather/historical')
  end

  def historical_min
    format_and_render(@historical_details_data, 'weather/historical_max', min_max: "Minimum")
  end

  def historical_max
    format_and_render(@historical_details_data, 'weather/historical_max', min_max: "Maximum")
  end

  def historical_avg
    average_temperature = calculate_average_temperature(@historical_hourly_data)
    render 'weather/historical_avg', locals: { average_temperature: average_temperature }
  end

  def by_time
    epoch_time = convert_to_epoch_time(date_and_time_params[:date], date_and_time_params[:time])
    weather = WeatherServiceByTime.new(@historical_hourly_data).closest_to(epoch_time)

    if weather.nil?
      render 'errors/404', locals: { error_message: 'Not Found' }
    else
      render 'weather/by_time', locals: { weather: weather }
    end
  end

  private

  def date_and_time_params
    params.permit(:date, :time)
  end

  def set_historical_hourly_data
    @historical_hourly_data ||= WeatherServiceHistoricalHourly.new.get_data_with_caching
  end

  def set_historical_details_data
    @historical_details_data ||= WeatherServiceHistoricalDetails.new.get_data_with_caching
  end

  def format_and_render(data, template, options = {})
    formatter = WeatherDataFormatter.new(data, options)
    formatted_data = formatter.format

    render template, locals: { formatted_data: formatted_data }
  end

  def convert_to_epoch_time(date, time)
    datetime = Time.strptime("#{date} #{time}", "%Y-%m-%d %H:%M").in_time_zone(Time.zone.name).in_time_zone(CITY_NAME)
    datetime.strftime('%s').to_i
  end

  def calculate_average_temperature(data)
    sum = 0
    count = data.size

    data.each do |item|
      sum += item["Temperature"]["Metric"]["Value"]
    end

    (sum/count).round(2)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApiWeather</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<p>
  <a href="/weather/current">Current Weather</a> |
  <a href="/weather/historical">24 hours weather</a> |
  <a href="/weather/historical/max">Max Temperature</a> |
  <a href="/weather/historical/min">Min Temperature</a> |
  <a href="/weather/historical/avg">Average Temperature</a> |
  <a href="/health">Status backend</a> |
</p>

<h2>Get weather by date</h2>
<%= form_with url: by_time_weather_path, method: :get do |form| %>
  <%= form.date_field :date, required: true %>
  <%= form.time_field :time, required: true %>
  <%= form.submit 'Get Weather' %>
<% end %>
<%= yield %>
</body>
</html>

app/views/weather/by_time.html.erb
<h1>By time</h1>

<p>
  Date: <%= weather[:date] %> <br>
  Temperature: <%= weather[:temperature] %> <%= weather[:temperature_unit] %><br>
  Weather: <%= weather[:weather] %>
</p>

app/views/weather/current.html.erb
<h1>Current Weather</h1>

<% formatted_data.each do |data| %>
  <p>
    Date: <%= data[:date] %><br>
    Temperature: <%= data[:temperature] %> <%= data[:temperature_unit] %><br>
    Weather: <%= data[:weather] %>
  </p>
<% end %>

app/views/weather/historical.html.erb
<h2>Historical Weather Data</h2>

<% formatted_data.each do |data| %>
  <p>
    Date: <%= data[:date] %> <br>
    Temperature: <%= data[:temperature] %> <%= data[:temperature_unit] %><br>
    Weather: <%= data[:weather] %>
  </p>
<% end %>

app/views/weather/historical_avg.html.erb
<h2>Average temperature</h2>

<p>Average temperature for 24 hours: <%= average_temperature %>°C</p>

app/views/weather/historical_max.html.erb
<h1>Maximum Temperature</h1>

<p>Maximum temperature: <%= formatted_data %>°C</p>

app/views/weather/historical_min.html.erb
<h1>Minimum Temperature</h1>

<p>Minimum temperature: <%= formatted_data %>°C</p>

app/views/weather/index.html.erb
<h1>City: Moscow</h1>

app/views/weather/not_found.html.erb
<h1>Error</h1>
<p><%= @error_message %></p>